#!/bin/bash
# Environment setup on CRCD. Submit it as a job rather than running it on a login
# node:
#
#   sbatch scripts/train/submit_setup.slurm
#
# It writes neologism/scripts/train/env.sh, which every other script sources.
#
# torch is NOT pip-installed. CRCD ships PyTorch as an Lmod module already built
# against the cluster's CUDA, and a venv created with --system-site-packages
# inherits it. Installing it with pip instead means unpacking ~6 GB of wheels,
# which is what kept getting OOM-killed, and it would be a build that has to be
# matched to the driver by hand.

set -euo pipefail

# `module` is a shell function, not a program, so it does not survive into a child
# process -- a batch script that runs this with `bash setup_env.sh` loses it, and a
# non-login shell never defined it in the first place. Re-initialise Lmod if needed.
if ! command -v module >/dev/null 2>&1; then
    for init in "${LMOD_PKG:-}/init/bash" /usr/share/lmod/lmod/init/bash \
                /etc/profile.d/lmod.sh /etc/profile.d/modules.sh; do
        [[ -f "$init" ]] && { source "$init"; break; }
    done
fi
command -v module >/dev/null 2>&1 || {
    echo "ERROR: the 'module' command is unavailable and Lmod could not be located."
    echo "Add '#SBATCH --export=ALL' or run this with 'bash -l', or source your"
    echo "site's Lmod init script before calling this one."
    exit 1
}

GROUP=$(id -gn)
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# home is capped at 75 GB and cannot be raised; /ix gets 5 TB
IX=${IX_ROOT:-/ix/$GROUP/$USER}
ENV_DIR=${ENV_DIR:-$IX/envs/neologism}
HF_CACHE=${HF_CACHE:-$IX/hf_cache}
MODEL_DIR=${MODEL_DIR:-$IX/model/google/gemma-3-4b-it}

echo "group     : $GROUP"
echo "ix root   : $IX"
echo "venv      : $ENV_DIR"
echo "hf cache  : $HF_CACHE"
echo "model dir : $MODEL_DIR"
echo

if [[ ! -d $(dirname "$IX") ]]; then
    echo "ERROR: $(dirname "$IX") does not exist. Check 'id -gn' and 'crc-quota',"
    echo "then re-run with:  IX_ROOT=/ix/<group>/$USER sbatch ..."
    exit 1
fi

# ---- find CRCD's prebuilt PyTorch module ------------------------------------
if [[ -z "${TORCH_MODULE:-}" ]]; then
    TORCH_MODULE=$(module -t spider pytorch 2>&1 | grep -oE '^python/pytorch[^ :]*' | sort -V | tail -1 || true)
fi

if [[ -n "$TORCH_MODULE" ]]; then
    echo "using prebuilt torch module: $TORCH_MODULE"
    PIP_TORCH=0
else
    echo "no python/pytorch* module found; falling back to pip-installing torch."
    echo "This needs several GB of RAM -- make sure the job has --mem=32G or more."
    echo "If a module does exist, find it with 'module spider pytorch' and re-run with"
    echo "  TORCH_MODULE=python/<name> sbatch ..."
    TORCH_MODULE=$(module -t spider python 2>&1 | grep -oE '^python/[^ :]*python3[^ :]*' | sort -V | tail -1 || true)
    [[ -n "$TORCH_MODULE" ]] || { echo "ERROR: no python module either"; exit 1; }
    echo "using plain python module: $TORCH_MODULE"
    PIP_TORCH=1
fi

module purge
module load "$TORCH_MODULE"

# ---- venv on top of the module ----------------------------------------------
# --system-site-packages is what lets the venv see the module's torch while still
# giving pip somewhere writable for everything else
mkdir -p "$(dirname "$ENV_DIR")" "$HF_CACHE"
if [[ ! -d "$ENV_DIR" ]]; then
    python -m venv --system-site-packages "$ENV_DIR"
fi
source "$ENV_DIR/bin/activate"

export TMPDIR=${TMPDIR:-$IX/tmp}
mkdir -p "$TMPDIR"

pip install --upgrade pip
if [[ "$PIP_TORCH" == "1" ]]; then
    pip install torch
fi
# Gemma3 needs transformers >= 4.50; --upgrade makes pip install into the venv when
# the module's copy is older, and leave it alone when it is new enough
pip install --upgrade 'transformers>=4.50' accelerate tqdm

# ---- verify ------------------------------------------------------------------
python - <<'PY'
import torch, transformers
print(f"\ntorch        {torch.__version__}   from {torch.__file__}")
print(f"transformers {transformers.__version__}")
print(f"cuda build   {torch.version.cuda}")
print(f"cuda visible {torch.cuda.is_available()}  "
      f"(False here is fine if this job has no GPU)")
PY

# ---- write the file every other script sources -------------------------------
cat > "$HERE/env.sh" <<INNER
# Generated by setup_env.sh -- machine-specific, not tracked in git.
# Source it in any shell or job:  source $HERE/env.sh
module purge
module load $TORCH_MODULE

# venv's activate script reads unset variables; put nounset back as we found it so
# sourcing this interactively does not break the shell
__neo_u=\$(shopt -po nounset || true)
set +u
source $ENV_DIR/bin/activate
eval "\$__neo_u"
unset __neo_u

export HF_HOME=$HF_CACHE
export NEOLOGISM_MODEL=$MODEL_DIR
export TMPDIR=$IX/tmp
export TOKENIZERS_PARALLELISM=false
INNER

echo
echo "wrote $HERE/env.sh"
echo
echo "next:"
echo "  1. accept the gemma-3 license at https://huggingface.co/google/gemma-3-4b-it"
echo "  2. on a login node:  source $HERE/env.sh && hf auth login"
echo "  3. sbatch $HERE/submit_download.slurm"
echo "  4. sbatch $HERE/submit_preflight.slurm"
