#!/bin/bash
# One-time environment setup on CRCD. Run it on a LOGIN node (it only downloads
# and installs; no heavy compute):
#
#   bash neologism/scripts/train/setup_env.sh
#
# It writes neologism/scripts/train/env.sh, which the Slurm scripts source. Nothing
# here touches ~/.bashrc: CRCD warns that `conda init` conflicts with their modules,
# so we use `source activate <prefix>` instead of `conda activate <name>`.

set -euo pipefail

GROUP=$(id -gn)
HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# The home directory is capped at 75 GB and cannot be raised, while /ix gives 5 TB.
# A conda env plus the model weights and the HF cache would eat a large slice of
# home, so everything lands on /ix.
IX=${IX_ROOT:-/ix/$GROUP/$USER}
ENV_PREFIX=${ENV_PREFIX:-$IX/envs/neologism}
HF_CACHE=${HF_CACHE:-$IX/hf_cache}
PYTHON_MODULE=${PYTHON_MODULE:-}

echo "group        : $GROUP"
echo "ix root      : $IX"
echo "conda env    : $ENV_PREFIX"
echo "hf cache     : $HF_CACHE"
echo

if [[ ! -d /ix/$GROUP ]]; then
    echo "ERROR: /ix/$GROUP does not exist."
    echo "Check your group with 'id -gn' and your allocations with 'crc-quota',"
    echo "then re-run with:  IX_ROOT=/ix/<group>/$USER bash $0"
    exit 1
fi

# ---- pick a python module ---------------------------------------------------
if [[ -z "$PYTHON_MODULE" ]]; then
    PYTHON_MODULE=$(module -t spider python 2>&1 | grep -E '^python/.*python3' | tail -1 || true)
fi
if [[ -z "$PYTHON_MODULE" ]]; then
    echo "ERROR: could not auto-detect a python module. Run 'module spider python',"
    echo "pick one, and re-run with:  PYTHON_MODULE=python/<version> bash $0"
    exit 1
fi
echo "python module: $PYTHON_MODULE"

module purge
module load "$PYTHON_MODULE"

# ---- create the environment -------------------------------------------------
mkdir -p "$IX/envs" "$HF_CACHE"
if [[ -d "$ENV_PREFIX" ]]; then
    echo "environment already exists, reusing it"
else
    conda create --yes --prefix "$ENV_PREFIX" python=3.11
fi

set +u                      # conda's activate script trips over `set -u`
source activate "$ENV_PREFIX"
set -u

# ---- dependencies -----------------------------------------------------------
# torch's default Linux wheel bundles its own CUDA runtime, so no cuda module is
# needed. accelerate is required by transformers' Trainer.
pip install --upgrade pip
pip install torch transformers accelerate tqdm

python - <<'PY'
import torch, transformers
print(f"\ntorch {torch.__version__} | transformers {transformers.__version__}")
print(f"CUDA build: {torch.version.cuda}  (torch.cuda.is_available() is False on a "
      f"login node -- that is expected, there is no GPU here)")
PY

# ---- write the file the Slurm scripts source --------------------------------
cat > "$HERE/env.sh" <<INNER
# Generated by setup_env.sh -- machine-specific, not tracked in git.
module purge
module load $PYTHON_MODULE
set +u
source activate $ENV_PREFIX
set -u
export HF_HOME=$HF_CACHE
export TOKENIZERS_PARALLELISM=false
INNER

echo
echo "wrote $HERE/env.sh"
echo
echo "next:"
echo "  1. accept the gemma-3 license at https://huggingface.co/google/gemma-3-4b-it"
echo "     (it is a gated model -- the download fails without this)"
echo "  2. hf auth login          # paste a token from hf.co/settings/tokens"
echo "  3. bash $HERE/download_model.sh"
echo "  4. crc-quota              # confirm you have room"
