#!/usr/bin/env python
"""Task 1 -- explicit part-of-speech probability.

Ask the model outright and read the answer off its probabilities:

    The part of speech of the word "WORD" is ___

Probability mass is summed over the surface forms each category can take, then
normalized across the three categories:

    P(category | word) = sum_{v in variants(category)} P(v | prompt)

Unlike Task 2 this needs no calibration -- there is no reference distribution
to fit and no slot to select, so the model's own probabilities are the answer.
What it does need is the same **evidence discipline**: accuracy is reported on
the Task 2 `final-test` words, which no part of either task was tuned on, so
the two probes are directly comparable on the same 234 items.

The one real design choice is which surface forms count. It is fixed in
advance, generated by rule rather than hand-listed, and governed by two
criteria that pull against each other.

**Cover the forms the model actually uses.** Not "give every category the same
number of spellings", which looks fair and is not:

  - Dropping " adj" costs the adjective category real mass, since a model
    asked for a part of speech says "adj" quite naturally.
  - Adding " n" and " v" to compensate would be far worse. They are single
    ambiguous tokens that collect mass from everything else those letters can
    start, inflating noun and verb for reasons unrelated to the question.

So " adj" is in and " n"/" v" are out. That asymmetry is a fact about English
abbreviation conventions, not a thumb on the scale.

**Keep the forms length-matched across categories.** The probability of a
surface form is a product over its tokens, so a longer form is intrinsically
smaller, and a category whose spellings tokenize longer is penalised for a
reason that has nothing to do with the word being classified. Under the Gemma
tokenizer the casings are badly uneven, and in *opposite directions*:

    " noun"    1     " Noun"       2 (_N+oun)      " NOUN"       2
    " verb"    1     " Verb"       1               " VERB"       2
    " adj"     1     " Adj"        1               " ADJ"        2
    " adjective" 1   " Adjective"  2 (_Ad+jective) " ADJECTIVE"  3 (_AD+JECT+IVE)

Title case hands verb a one-token spelling where noun gets two; upper case
costs adjective three tokens where noun pays two. Neither slant is principled
-- it is just how the vocabulary happens to have been carved.

Articles, by contrast, are length-neutral: exactly one extra token for every
category. So the default set is **lowercase only, with and without the
article**, which is length-matched position for position:

    noun   " noun"(1)        " a noun"(2)
    verb   " verb"(1)        " a verb"(2)
    adj    " adjective"(1)   " an adjective"(2)
           " adj"(1)         " an adj"(2)

Casing applies to the whole answer, never to one part of it: an answer is
" a noun", " A Noun" or " A NOUN", never " A noun". Handling the article and
the label independently is what produced an earlier version in which " A noun"
was covered but " Noun" was not.

`--casings lower,title,upper` adds the cased levels back, `--no-abbrev` drops
" adj", `--no-articles` drops the articled forms, and `--report-sensitivity`
reports every such set side by side, so each choice is shown to be worth
little rather than assumed to be.

    python Task_1/run_task1.py --model google/gemma-3-4b-it --report-sensitivity
"""

from __future__ import annotations

import argparse
import json
import math
from collections import Counter
from pathlib import Path
from typing import Dict, List

POS_KEYS = ("noun", "verb", "adj")

PROMPT = 'The part of speech of the word "{WORD}" is'

#: Canonical label for each category.
LABELS: Dict[str, List[str]] = {
    "noun": ["noun"],
    "verb": ["verb"],
    "adj": ["adjective"],
}

#: Abbreviations, included by default. Only "adj" qualifies: it is what a model
#: actually writes, and it is unambiguous as an answer to this prompt. "n" and
#: "v" are deliberately absent -- they would not restore symmetry, they would
#: break it, by collecting probability mass from every other continuation those
#: letters can begin. `--no-abbrev` reports what the choice is worth.
ABBREVIATIONS: Dict[str, List[str]] = {
    "noun": [],
    "verb": [],
    "adj": ["adj"],
}


#: How a whole answer may be cased. Casing applies to the answer, not to its
#: parts: an answer is written " a noun", " A Noun" or " A NOUN", never
#: " A noun". Treating the article and the label as independently cased is what
#: produced the earlier inconsistency where " A noun" was covered but " Noun"
#: was not.
CASINGS = {
    "lower": str.lower,
    "title": str.capitalize,
    "upper": str.upper,
}


def article_for(word: str) -> str:
    return "an" if word[:1].lower() in set("aeiou") else "a"


def build_variants(with_articles: bool = True,
                   casings: tuple = ("lower",),
                   with_abbrev: bool = True) -> Dict[str, List[str]]:
    """Surface forms per category, generated by the same rule for each.

    Casing is applied uniformly across the answer, so each casing level adds
    the same number of forms to every category and the article never disagrees
    with the label it introduces.
    """
    out: Dict[str, List[str]] = {}
    for cat in POS_KEYS:
        labels = list(LABELS[cat]) + (ABBREVIATIONS[cat] if with_abbrev else [])
        forms = []
        for label in labels:
            for name in casings:
                case = CASINGS[name]
                # The article is chosen from the lowercase label -- "adjective"
                # takes "an" whatever its casing -- then cased to match.
                bare = case(label)
                forms.append(" " + bare)
                if with_articles:
                    forms.append(f" {case(article_for(label))} {bare}")
        # Order is irrelevant to the sum, but dedupe so nothing is counted twice.
        out[cat] = sorted(set(forms))
    return out


def aggregate(logps: Dict[str, float],
              variants: Dict[str, List[str]]) -> Dict[str, float]:
    """P(category | word) from one word's per-variant log probabilities.

    Kept separate from scoring so that a different variant set costs nothing:
    the minimal set is a subset of the full one, so the sensitivity check
    re-reads the same numbers rather than re-running the model.
    """
    mass = {cat: sum(math.exp(logps[v]) for v in variants[cat])
            for cat in POS_KEYS}
    total = sum(mass.values()) or 1.0
    return {cat: mass[cat] / total for cat in POS_KEYS}


def load_model(name: str, device: str | None = None, dtype: str = "bfloat16"):
    """The tokenizer and model, on the best device available."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    device = device or ("cuda" if torch.cuda.is_available()
                        else "mps" if torch.backends.mps.is_available()
                        else "cpu")
    td = getattr(torch, dtype) if device != "cpu" else torch.float32
    print(f"model={name}  device={device}  dtype={td}")
    tok = AutoTokenizer.from_pretrained(name)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "right"
    model = AutoModelForCausalLM.from_pretrained(name, torch_dtype=td).to(device).eval()
    return tok, model, device


def score_log_probs(tok, model, device, words: List[str], forms: List[str],
                    batch_size: int = 64, label: str = "") -> Dict[str, Dict[str, float]]:
    """log P(form | prompt about word), for every (word, form) pair.

    Returns the raw log probabilities rather than category probabilities, so
    that any variant set can be aggregated from them afterwards without
    touching the GPU again.
    """
    import torch

    out: Dict[str, Dict[str, float]] = {w: {} for w in words}
    # One (prompt, form) pair per row: a form can be several tokens, so its
    # probability is a product over them -- teacher forcing, not a single
    # next-token distribution.
    rows = [(w, v) for w in words for v in forms]
    with torch.no_grad():
        for i in range(0, len(rows), batch_size):
            chunk = rows[i:i + batch_size]
            prompts = [PROMPT.replace("{WORD}", w) for w, _ in chunk]
            enc = tok([p + v for p, (_, v) in zip(prompts, chunk)],
                      return_tensors="pt", padding=True,
                      add_special_tokens=True).to(device)
            pre = tok(prompts, add_special_tokens=True)["input_ids"]
            lg = model(**enc).logits.float().log_softmax(-1)
            ids, mask = enc["input_ids"], enc["attention_mask"]
            for j, (w, v) in enumerate(chunk):
                n_total, n_pre = int(mask[j].sum()), len(pre[j])
                out[w][v] = sum(lg[j, t - 1, ids[j, t]].item()
                                for t in range(n_pre, n_total))
            if label and (i // batch_size) % 20 == 0:
                print(f"  {label}: {min(i + batch_size, len(rows)):>6}/{len(rows)}",
                      flush=True)
    return out


def accuracy_report(results: Dict[str, Dict[str, Dict[str, float]]],
                    title: str) -> dict:
    """Three-way accuracy with a confusion matrix, printed and returned."""
    print(f"\n{title}")
    print(f"{'':8}{'n':>5}{'答对':>7}{'准确率':>9}")
    report: dict = {}
    conf = {t: Counter() for t in POS_KEYS}
    correct = total = 0
    for t in POS_KEYS:
        hits = 0
        for _, pr in results[t].items():
            pred = max(pr, key=pr.get)
            conf[t][pred] += 1
            hits += pred == t
        report[t] = {"n": len(results[t]), "correct": hits,
                     "accuracy": round(hits / len(results[t]), 4)}
        correct += hits
        total += len(results[t])
        print(f"{t:<8}{report[t]['n']:>5}{hits:>7}{report[t]['accuracy']:>9.3f}")
    overall = correct / total
    print("-" * 29)
    print(f"{'总体':<7}{total:>5}{correct:>7}{overall:>9.3f}")
    se = math.sqrt(overall * (1 - overall) / total)
    print(f"95% CI  [{overall - 1.96 * se:.3f}, {overall + 1.96 * se:.3f}]")
    print("\n混淆矩阵（行=真实，列=预测）")
    print(f"{'':8}" + "".join(f"{p:>7}" for p in POS_KEYS))
    for t in POS_KEYS:
        print(f"{t:<8}" + "".join(f"{conf[t][p]:>7}" for p in POS_KEYS))
    report["overall"] = round(overall, 4)
    report["ci95"] = [round(overall - 1.96 * se, 4), round(overall + 1.96 * se, 4)]
    report["confusion"] = {t: dict(conf[t]) for t in POS_KEYS}
    return report


def main() -> None:
    here = Path(__file__).resolve().parent
    task2 = here.parent / "Task_2" / "out"
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", default="google/gemma-3-4b-it")
    ap.add_argument("--words", type=Path, default=task2 / "control_finaltest.json",
                    help="a control-word file, or a JSON list of words to score")
    ap.add_argument("--out", type=Path, default=here / "out" / "task1.json")
    ap.add_argument("--batch-size", type=int, default=64)
    ap.add_argument("--device", default=None)
    ap.add_argument("--dtype", default="bfloat16")
    ap.add_argument("--no-articles", action="store_true")
    ap.add_argument("--casings", default="lower",
                    help="comma-separated subset of lower,title,upper. Only "
                         "lower by default: the cased forms tokenize to "
                         "unequal lengths across the three categories")
    ap.add_argument("--no-abbrev", action="store_true",
                    help='drop " adj"; on by default because the model uses it')
    ap.add_argument("--report-sensitivity", action="store_true",
                    help="also report accuracy under the alternative variant sets")
    args = ap.parse_args()

    tok, model, device = load_model(args.model, args.device, args.dtype)

    raw = json.loads(args.words.read_text())
    labelled = isinstance(raw, dict) and "words" in raw
    words: Dict[str, List[str]] = raw["words"] if labelled else {"unlabelled": raw}
    print(", ".join(f"{k}={len(v)}" for k, v in words.items()))

    arts, abbr = not args.no_articles, not args.no_abbrev
    cases = tuple(c.strip() for c in args.casings.split(",") if c.strip())
    unknown = [c for c in cases if c not in CASINGS]
    if unknown:
        ap.error(f"--casings 只接受 {', '.join(CASINGS)}；不认识 {unknown}")

    variants = build_variants(arts, cases, abbr)
    # Each alternative isolates one decision, so the sensitivity table shows
    # what that decision alone is worth. The two casing levels are listed
    # separately because their token-length bias runs in opposite directions:
    # " Verb" is one token where " Noun" is two, while " ADJECTIVE" is three
    # where " NOUN" is two.
    alternatives = {
        "+首字母大写": build_variants(arts, cases + ("title",), abbr),
        "+全大写": build_variants(arts, cases + ("upper",), abbr),
        "三种大小写全上": build_variants(arts, ("lower", "title", "upper"), abbr),
        "无缩写 (--no-abbrev)": build_variants(arts, cases, False),
        "无冠词 (--no-articles)": build_variants(False, cases, abbr),
        "最小集（各 1 个单 token 标签）": build_variants(False, ("lower",), False),
    }
    alternatives = {k: v for k, v in alternatives.items() if v != variants}
    if not args.report_sensitivity:
        alternatives = {}       # nothing to re-aggregate, so nothing to score

    # Probability of a surface form is a product over its tokens, so a longer
    # form is intrinsically smaller. Print the counts: if one category's
    # variants are systematically longer, its summed mass is depressed for a
    # reason that has nothing to do with the word being classified.
    def ntok(v: str) -> int:
        return len(tok.encode(v, add_special_tokens=False))

    print("\n每类的表层变体（括号内为 token 数）：")
    for cat in POS_KEYS:
        shown = "  ".join(f"{v!r}({ntok(v)})" for v in variants[cat])
        lens = [ntok(v) for v in variants[cat]]
        print(f"  {cat:<5} {len(variants[cat]):>2} 个，token 数 "
              f"{min(lens)}-{max(lens)}（均 {sum(lens) / len(lens):.2f}）\n"
              f"        {shown}")
    if alternatives:
        print("\n敏感性检查还会报告：" + "、".join(alternatives))

    # Score each surface form once. Every set to be reported draws from this
    # union, so the sensitivity report is pure re-aggregation -- no second pass.
    forms = sorted({v for d in [variants, *alternatives.values()]
                    for c in POS_KEYS for v in d[c]})
    print(f"需要打分的表层形式：{len(forms)} 个"
          + (f"（主集 {sum(len(variants[c]) for c in POS_KEYS)} 个，"
             f"其余供敏感性检查复用）" if alternatives else ""))

    logps = {pos: score_log_probs(tok, model, device, ws, forms,
                                  args.batch_size, label=pos)
             for pos, ws in words.items()}

    def probabilities(vset) -> Dict[str, Dict[str, Dict[str, float]]]:
        return {t: {w: aggregate(lp, vset) for w, lp in d.items()}
                for t, d in logps.items()}

    results = probabilities(variants)
    scorable = labelled and set(words) == set(POS_KEYS)

    report = accuracy_report(results, "主变体集") if scorable else {}
    sensitivity: Dict[str, dict] = {}
    if args.report_sensitivity:
        for name, vset in alternatives.items():
            alt = probabilities(vset)
            entry: dict = {"variants": vset, "probabilities": alt}
            if scorable:
                entry["accuracy"] = accuracy_report(alt, f"敏感性：{name}")
            sensitivity[name] = entry
        if scorable and sensitivity:
            # The point of the table: the variant set is Task 1's only design
            # choice, so the conclusion has to survive changing it.
            print(f"\n变体集敏感性\n{'':34}{'noun':>8}{'verb':>8}"
                  f"{'adj':>8}{'overall':>10}{'Δ':>9}")
            rows = [("主变体集", report)] + [(n, e["accuracy"])
                                             for n, e in sensitivity.items()]
            for name, r in rows:
                d = r["overall"] - report["overall"]
                print(f"{name:<32}" + "".join(f"{r[p]['accuracy']:>8.3f}"
                                              for p in POS_KEYS)
                      + f"{r['overall']:>10.3f}"
                      + ("        —" if r is report else f"{d:>+9.3f}"))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps({
        "model": args.model,
        "prompt": PROMPT,
        "variants": variants,
        "words_file": str(args.words),
        "accuracy": report,
        "probabilities": results,
        "sensitivity": sensitivity,
        # Kept so any other variant set can be evaluated without the GPU.
        "log_probabilities": logps,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n-> {args.out}")


if __name__ == "__main__":
    main()
